// <auto-generated />
using System;
using GestionDesProjectBackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionDesProjectBackEnd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionDesProjectBackEnd.Models.AppUsers", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUser")
                        .HasName("PK__AppUsers__3214EC076F73C946");

                    b.ToTable("AppUsers", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("AppUsers");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GestionDesProjectBackEnd.Models.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Equipe");
                });

            modelBuilder.Entity("GestionDesProjectBackEnd.Models.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckoutDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Tasks__3214EC070CE2E8C2");

                    b.HasIndex("IdMembers");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("GestionDesProjectBackEnd.Models.Admin", b =>
                {
                    b.HasBaseType("GestionDesProjectBackEnd.Models.AppUsers");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Poste")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("GestionDesProjectBackEnd.Models.Members", b =>
                {
                    b.HasBaseType("GestionDesProjectBackEnd.Models.AppUsers");

                    b.Property<int?>("EquipeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Poste")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("EquipeId");

                    b.ToTable("AppUsers", t =>
                        {
                            t.Property("FirstName")
                                .HasColumnName("Members_FirstName");

                            t.Property("LastName")
                                .HasColumnName("Members_LastName");

                            t.Property("PhoneNumber")
                                .HasColumnName("Members_PhoneNumber");

                            t.Property("Poste")
                                .HasColumnName("Members_Poste");

                            t.Property("Username")
                                .HasColumnName("Members_Username");
                        });

                    b.HasDiscriminator().HasValue("Member");
                });

            modelBuilder.Entity("GestionDesProjectBackEnd.Models.Tasks", b =>
                {
                    b.HasOne("GestionDesProjectBackEnd.Models.Members", "IdMembersNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("IdMembers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tasks_Members");

                    b.Navigation("IdMembersNavigation");
                });

            modelBuilder.Entity("GestionDesProjectBackEnd.Models.Members", b =>
                {
                    b.HasOne("GestionDesProjectBackEnd.Models.Equipe", "Equipe")
                        .WithMany("Members")
                        .HasForeignKey("EquipeId")
                        .HasConstraintName("FK_Members_Equipe");

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("GestionDesProjectBackEnd.Models.Equipe", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("GestionDesProjectBackEnd.Models.Members", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
